{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.2.1.jar",
          "url": "gradle-8.2.1.jar",
          "size": 11652537,
          "sha512": "e4161bb58b5dfc622e8197131df9c44c5bffdeda962b531b50b6e05ed0a6c6616e4ae0aec5aacfb41137622324578c807ca61b5da5fdccdc796404cc6022fc3a",
          "sha256": "a1b8fd78c0fc035a6b6988b6bf260d7976eecc03051c311aa285d437e221e640",
          "sha1": "f6560b3e785cc28f3d391a7e9a29c6c41491d3fc",
          "md5": "738062c0c1f6c8602d7fb881fbd7e90f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "8.2.1-10154469"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-ddmlib-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-additional-test-output-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-coverage-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-emulator-control-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-logcat-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-apk-installer-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-retention-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-result-listener-gradle-proto",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "2.0.0-deprecated-use-gradle-api"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.19.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-core",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.45.1"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.8-alpha08"
          }
        },
        {
          "group": "com.google.flatbuffers",
          "module": "flatbuffers-java",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.1.0-rc2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-8.2.1.jar",
          "url": "gradle-8.2.1.jar",
          "size": 11652537,
          "sha512": "e4161bb58b5dfc622e8197131df9c44c5bffdeda962b531b50b6e05ed0a6c6616e4ae0aec5aacfb41137622324578c807ca61b5da5fdccdc796404cc6022fc3a",
          "sha256": "a1b8fd78c0fc035a6b6988b6bf260d7976eecc03051c311aa285d437e221e640",
          "sha1": "f6560b3e785cc28f3d391a7e9a29c6c41491d3fc",
          "md5": "738062c0c1f6c8602d7fb881fbd7e90f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.2.1-javadoc.jar",
          "url": "gradle-8.2.1-javadoc.jar",
          "size": 650478,
          "sha512": "ad8dba54065a41834946522029df32d807e25b732426740c44af76796ff963df598507c9c8959b97816a8afa5d8bb46e341032c7fd88beba36957eed813c04d0",
          "sha256": "be0e5bad247bf5ae7c2e0e53e50ef2665e9c95d8551fedebcce41e404fd954b4",
          "sha1": "09eb5fecde7e0b1b25b8abcf62a9c61f2b2dab9c",
          "md5": "63e4a5e6bfc12f0e3a15d89af7f4b8d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-8.2.1-sources.jar",
          "url": "gradle-8.2.1-sources.jar",
          "size": 3662410,
          "sha512": "f0304b1d79d304690bae18609a6ef84a2cdd3d73a4c9d8a5713284e37477130c0438c12ffad111cfcd67d8576fd4b6e871cfcabd7cc55d1b5b997328d700b8b2",
          "sha256": "7e029b616aa9c1f6ee34319009f493837f77d29a5aafbff51882134bc087a493",
          "sha1": "ab8448653544356d30a3d839df3200c576c9164a",
          "md5": "8f834dba095a21a8c91dc0db25870365"
        }
      ]
    }
  ]
}
