{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.1.jar",
          "url": "builder-8.2.1.jar",
          "size": 12168684,
          "sha512": "81cdea167f318bca1faea927025f2d4e814ce0605490b65c7c7203f3d318d43226a24c33405eccba26e9032ae0e89e3834256c12bab1c246ff34325e6e1a736d",
          "sha256": "4810115b830a27dc75afa0ba92895d6eefacc680f881124a5088314ab68c3711",
          "sha1": "64845916bd7f31f6494e9ffd9c2e1337056ddfce",
          "md5": "020f5bbb8149c1338ade14670e06399d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.1"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.1.jar",
          "url": "builder-8.2.1.jar",
          "size": 12168684,
          "sha512": "81cdea167f318bca1faea927025f2d4e814ce0605490b65c7c7203f3d318d43226a24c33405eccba26e9032ae0e89e3834256c12bab1c246ff34325e6e1a736d",
          "sha256": "4810115b830a27dc75afa0ba92895d6eefacc680f881124a5088314ab68c3711",
          "sha1": "64845916bd7f31f6494e9ffd9c2e1337056ddfce",
          "md5": "020f5bbb8149c1338ade14670e06399d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.1-javadoc.jar",
          "url": "builder-8.2.1-javadoc.jar",
          "size": 400792,
          "sha512": "e40643595e634d5decf5dec5eda0400be6b86390b6947738ee52659e60347ef5d2e8faa56a0376823a0a910e791cd3121d20ad92b65f3ad34432f6d5793d4e50",
          "sha256": "b90b5e2894afb49c930a00d8e06df5a26e4bb1442585b1fe3f5e9ee8c1c400cb",
          "sha1": "cd1cc8071bfa636241e1368bc7e5fd7258a27c07",
          "md5": "276eb8e85dcdeabcccb62592ebc04ad8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.1-sources.jar",
          "url": "builder-8.2.1-sources.jar",
          "size": 281987,
          "sha512": "3e67b5af657ffecb397e97af2051c906fad4de9a04ddfc2b37ffa8b3bfeb96489272dac2c4517628f85484a64f6eeaf7c9082eca4b06efa3032a9c331bb88f7a",
          "sha256": "619897feb9b05209850053b62b4e43c27486a130a68c90d1bc5f6c8433cdbcf8",
          "sha1": "5788cf9afbf50a4d91c50f5b91e8b21ac4c67c42",
          "md5": "430f4e3304f9a5bd2f06bfcc5016de59"
        }
      ]
    }
  ]
}
