require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityAdmob', :path => '../../node_modules/@capacitor-community/admob'
  pod 'CapacitorDevice', :path => '../../node_modules/@capacitor/device'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  # The AdMob plugin (6.x) uses the pre-3.0 UMP consent API names
  # (UMPConsentStatus etc.); UMP 3.x renamed them and breaks the build.
  pod 'GoogleUserMessagingPlatform', '~> 2.7'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
